### ISSUE TITLE
Returning code 500

### ISSUE THREAD

**Issue by moo-d** [yandricr/gpti-js#10]
Hello, I use bing as you wrote in readme.md. but returns 500

```js
{
  code: 500,
  status: false,
  error: 'INTERNAL_SERVER_ERROR',
  message: 'general (unknown) error'
}
```

**Comment by yandricr** [comment]
I managed to solve the problem that requires Bing chat, I hope it doesn't happen again

**Comment by yandricr** [comment]
I'm going to see what I can do but I already found the error that requires bing chat.

**Comment by yandricr** [comment]
It's already fixed, it took me a while to figure out what's wrong and it turned out that cookies were needed, but it now works, I hope there isn't another error

**Comment by moo-d** [comment]
It works now, thanks
