### ISSUE TITLE
INTERNAL_SERVER_ERROR, general (unknown) error

### ISSUE THREAD

**Issue by FaryarKankash** [yandricr/gpti-js#11]
when i use bing model i get this {"code":500,"status":false,"error":"INTERNAL_SERVER_ERROR","message":"general (unknown) error"},
it's only on bing model, gpt and others are fine

**Comment by yandricr** [comment]
Bing has made some modifications to its Copilot function, which now requires the use of Captcha. However, when using this functionality, it may have intermittent issues, which means it may work correctly in some cases and not allow the use of Bing in others. Unfortunately, I have not yet found a solution to fix this problem
