### ISSUE TITLE
GPT Web

### ISSUE THREAD

**Issue by moo-d** [yandricr/gpti-js#12]
Can you get gptweb working to connect messages?

I mean like
```js
gptweb({
  message: [],
  promp: "Are you familiar with the movie Wonka released in 2023?",
  markdown: false
} ...)
```

**Comment by yandricr** [comment]
While I can add the history function, unfortunately it does not provide satisfactory results when searching on the internet

**Comment by moo-d** [comment]
Got it. Thank you for explaining.
