### ISSUE TITLE
StableDifusion Not Working!

### ISSUE THREAD

**Issue by max1mde** [yandricr/gpti-js#14]
I tried the XL and V2 version but even with the default prompt they are not working!
![image](https://github.com/yandricr/gpti-js/assets/114857048/1fb484d0-2287-41fd-a2b4-db8d608ef5d2)
![image](https://github.com/yandricr/gpti-js/assets/114857048/06758252-89b1-420c-b0c7-cdfb6c32d7fb)

(GPT 4 works for me tho)

**Comment by yandricr** [comment]
This model works very well for me, although there may be a small error that is automatically fixed afterward

**Comment by max1mde** [comment]
I still dont know what causes the issue...
![image](https://github.com/yandricr/gpti-js/assets/114857048/822f86b5-aabe-4443-af19-408a77c1636f)

Can you show me your working code?

**Comment by yandricr** [comment]
I understand you're experiencing issues with the Stable-Diffusion XL model, which can be frustrating. It seems that it's currently under maintenance, but once it's back up and running, it will automatically update in the package. In the meantime, you can explore other available models or continue using this one as a reference. Additionally, if you need an immediate alternative, you can also turn to Bing, as I recently resolved the issue I encountered, so it's now available for use again

**Comment by yandricr** [comment]
Remember that any model from this package that belongs to my API will be automatically available, so don't worry if one doesn't work

**Comment by max1mde** [comment]
There is no working image API for me

**Comment by yandricr** [comment]
The image generation model does work for me
![ts](https://github.com/yandricr/gpti-js/assets/77084669/260a2233-ae57-45f2-9381-d6ee2543d29c)
![console](https://github.com/yandricr/gpti-js/assets/77084669/364a9e01-f5e2-4baa-8dd3-b3a3cd41427a)

**Comment by max1mde** [comment]
Oh sorry looks like it was my fault.. I replaced my entire code with that example and now it works somehow
![image](https://github.com/yandricr/gpti-js/assets/114857048/1044d3fb-5517-4d8d-8a2f-1ddc53024fb8)
but thanks for the help
