### ISSUE TITLE
Emi model doesn't work

### ISSUE THREAD

**Issue by Paxsenix0** [yandricr/gpti-js#15]
Hello! Thank you for this free services!
Recently when i tried to use Emi model, i keep getting error code 500

```
{
    "code": 500,
    "status": false,
    "error": "INTERNAL_SERVER_ERROR",
    "message": "general (unknown) error"
}
```

**Comment by yandricr** [comment]
The model works correctly for me

![5ef5d682-6d5e-4794-9897-77ef18e5c2e5](https://github.com/yandricr/gpti-js/assets/77084669/b4487602-634d-469b-8e1a-9aa8cb53bd03)

**Comment by Paxsenix0** [comment]
It's working now, thank you, i guess it's because of my prompt that too long.

Once again thank you!!
