### ISSUE TITLE
When using Bing, it shows Internal Server Error

### ISSUE THREAD

**Issue by OFFICIAL-DARK-BEAST** [yandricr/gpti-js#18]
![image](https://github.com/yandricr/gpti-js/assets/79217491/febdde38-1e92-47f7-b033-e161bacb8a51)

**Comment by OFFICIAL-DARK-BEAST** [comment]
Same for LLaMA-2

**Comment by yandricr** [comment]
The issue with Bing will automatically be fixed after some time, but Llama2 has not been working for a while now. However, I'm going to add that model back soon

**Comment by yandricr** [comment]
The issue with Bing will automatically be fixed after some time, but Llama2 has not been working for a while now. However, I'm going to add that model back soon
