### ISSUE TITLE
It returns object with id and status "initiation" instead of actual response from LLM

### ISSUE THREAD

**Issue by gerkim62** [yandricr/gpti-js#21]
code that was working a while ago now returns {
id:string,
status:"initiation"
}

instead of `code: number;
    status: boolean;
    model: string;
    gpt: string;
    original: string | null` | `{
    code: number;
    error: string;
    message: string;
}`

i dont see any updates in docs. what changed?

**Comment by yandricr** [comment]
Hi! For now, I don't have a specific date for the next update of this package.
Please note that it can be somewhat heavy when installing it in your project.
However, you can easily code it yourself by following this guide: https://nexra.aryahcr.cc/documentation/en

**Comment by gerkim62** [comment]
it seems the package is returning different response than the one it used to return before. did anything change?

**Comment by yandricr** [comment]
I only changed the structure of my API, everything still works the same
just check the documentation, as the code is the same as in this package
I only modified the organization of the structure

**Comment by gerkim62** [comment]
thank you for your reply. and i appreciate you taking time to create this package,

however am not sure if i understand you correctly when you say everything works the same.
the same code `await gpt.v1({
      prompt: prompt,
      model: "GPT-4",
      markdown: true,
    });`
    
    that was working suddenly stopped working without any changes from my end. as in my first comment, it is no longer returning the same json object as before. maybe gpt-4 is no longer supported without providing an api key or something?
    
    once again thanks for this helpful package

**Comment by gerkim62** [comment]
This package is no longer working even the examples in readme do not work
