### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by erturkdotgg** [yandricr/gpti-js#4]
Module is not working right now.

**Comment by yandricr** [comment]
Yes, I just realized, in a moment I will update with the same models, menox lexica, but very soon I will add new models that I already have for my api and the package, it just killed my replit api

I'm sorry if there were any problems with your projects

**Comment by yandricr** [comment]
You can now use gpt again, now that you can memorize the messages, the more new models, I will soon add more that I already have, but it is difficult for me to update

**Comment by erturkdotgg** [comment]
> You can now use gpt again, now that you can memorize the messages, the more new models, I will soon add more that I already have, but it is difficult for me to update

Thank you!!
